FROM registry.access.redhat.com/ubi9/ubi:latest AS certs
RUN dnf -y install ca-certificates && \
    update-ca-trust && \
    cp /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem /tmp/ca-certificates.crt && \
    dnf clean all && \
    rm -rf /var/cache/dnf

FROM registry.access.redhat.com/ubi9/ubi-micro:latest

LABEL maintainer="Ruohang Feng (@Vonng) <rh@vonng.com>" \
      vendor="PGSTY" \
      url="https://silo.pgsty.com" \
      org.opencontainers.image.vendor="PGSTY" \
      org.opencontainers.image.url="https://silo.pgsty.com" \
      org.opencontainers.image.source="https://github.com/pgsty/mc" \
      org.opencontainers.image.description="Silo object storage client (mcli), a community-maintained fork of the MinIO Client." \
      org.opencontainers.image.licenses="AGPL-3.0-or-later" \
      description="Silo object storage client (mcli), a community-maintained fork of the MinIO Client."

COPY --from=certs /tmp/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY mc /usr/bin/mc
COPY LICENSE /licenses/LICENSE
COPY CREDITS /licenses/CREDITS

RUN chmod +x /usr/bin/mc

ENTRYPOINT ["/usr/bin/mc"]
