FROM registry.access.redhat.com/ubi8/ubi-minimal:8.8

LABEL maintainer="pgsty <https://github.com/pgsty/mc>"

COPY mc /usr/bin/
COPY CREDITS /licenses/CREDITS
COPY LICENSE /licenses/LICENSE

RUN  \
     microdnf update --nodocs --assumeyes && \
     microdnf install ca-certificates --nodocs --assumeyes && \
     microdnf clean all

ENTRYPOINT ["mc"]
