#!/usr/bin/env bash

set -euo pipefail

# Regenerates CREDITS from every Go module linked into any released mcli
# binary. Tool and test-only dependencies stay out; platform-specific runtime
# modules enter through the union of the six GoReleaser targets.

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_dir="$(cd "${script_dir}/.." && pwd)"
cd "${repo_dir}"

out_file="${1:-${repo_dir}/CREDITS}"
tmp_file="${out_file}.tmp"
module_file="$(mktemp)"
trap 'rm -f "${tmp_file}" "${module_file}"' EXIT

rule_dash='----------------------------------------------------------------'
rule_equal='================================================================'
release_targets='linux/amd64 linux/arm64 darwin/amd64 darwin/arm64 windows/amd64 windows/arm64'

# These modules publish Go standard-library-derived source without a license
# file. Their source headers point to the Go project BSD license.
stdlib_derived='github.com/minio/colorjson github.com/minio/filepath'

is_stdlib_derived() {
  case " ${stdlib_derived} " in
    *" $1 "*) return 0 ;;
    *) return 1 ;;
  esac
}

emit_text() {
  printf '%s\n' "$(cat "$1")"
}

module_url() {
  local path="$1"
  if [[ "${path}" =~ ^(github\.com/[^/]+/[^/]+)/v[0-9]+$ ]]; then
    path="${BASH_REMATCH[1]}"
  fi
  printf 'https://%s\n' "${path}"
}

go mod download

go_license="$(go list -m -f '{{.Dir}}' golang.org/x/sys)/LICENSE"
if [ ! -f "${go_license}" ]; then
  echo "Missing Go license text: ${go_license}" >&2
  exit 1
fi

for target in ${release_targets}; do
  goos="${target%/*}"
  goarch="${target#*/}"
  GOOS="${goos}" GOARCH="${goarch}" CGO_ENABLED=0 \
    go list -deps -tags kqueue \
      -f '{{if and (not .Standard) .Module}}{{.Module.Path}}{{end}}' .
done | LC_ALL=C sort -u | grep -vx 'github.com/minio/mc' > "${module_file}"

{
  printf '%s\n' \
    'mcli bundles third-party software under the licenses reproduced below.' \
    'Generated by buildscripts/gen-credits.sh (make credits) from the union' \
    'of Go modules linked into all release binaries. Do not edit by hand.' \
    '' \
    "${rule_equal}" \
    ''
  printf '%s\n%s\n%s\n' 'Go (the standard library)' 'https://golang.org/' "${rule_dash}"
  emit_text "${go_license}"
  printf '\n%s\n' "${rule_equal}"

  while IFS= read -r path; do
    metadata="$(go list -m -f '{{.Path}}|{{with .Replace}}{{.Path}}{{end}}|{{.Dir}}' "${path}")"
    IFS='|' read -r module_path replacement dir <<< "${metadata}"
    if [ -z "${dir}" ] || [ ! -d "${dir}" ]; then
      echo "Module cache directory missing for ${module_path}" >&2
      exit 1
    fi

    name="${module_path}"
    url="$(module_url "${module_path}")"
    if [ -n "${replacement}" ] && [ "${replacement}" != "${module_path}" ]; then
      name="${module_path} (replaced by ${replacement})"
      url="$(module_url "${replacement}")"
    fi
    printf '\n%s\n%s\n%s\n' "${name}" "${url}" "${rule_dash}"

    if is_stdlib_derived "${module_path}"; then
      printf '%s\n%s\n\n' \
        'This module republishes Go standard-library-derived code without a' \
        'license file; the Go project license below applies per its headers.'
      emit_text "${go_license}"
    elif [ "${module_path}" = 'github.com/mattn/go-localereader' ]; then
      emit_text "${script_dir}/license-overrides/github.com_mattn_go-localereader.LICENSE"
    else
      license_files=()
      for candidate in LICENSE LICENSE.txt LICENSE.md LICENSE.Golang LICENSE.libyaml LICENCE LICENCE.txt COPYING COPYING.txt UNLICENSE; do
        if [ -f "${dir}/${candidate}" ]; then
          license_files+=("${dir}/${candidate}")
        fi
      done
      if [ "${#license_files[@]}" -eq 0 ]; then
        echo "No license file found for ${module_path} in ${dir}" >&2
        exit 1
      fi
      for license_file in "${license_files[@]}"; do
        if [ "${#license_files[@]}" -gt 1 ]; then
          printf '%s\n\n' "Bundled license file: $(basename "${license_file}")"
        fi
        emit_text "${license_file}"
        printf '\n'
      done
    fi

    if [ "${module_path}" = 'github.com/prometheus/client_golang' ]; then
      nested_license="${dir}/internal/github.com/golang/gddo/LICENSE"
      if [ ! -f "${nested_license}" ]; then
        echo "Missing embedded gddo license in ${module_path}" >&2
        exit 1
      fi
      printf '\n%s\n\n' 'Bundled license file: internal/github.com/golang/gddo/LICENSE'
      emit_text "${nested_license}"
    fi

    for notice in NOTICE NOTICE.txt PATENTS PATENTS.txt; do
      if [ -f "${dir}/${notice}" ]; then
        printf '\n%s\n\n' "Bundled notice file: ${notice}"
        emit_text "${dir}/${notice}"
      fi
    done
    printf '\n%s\n' "${rule_equal}"
  done < "${module_file}"
} > "${tmp_file}"

mv "${tmp_file}" "${out_file}"
